[[main]]
  identifier = "about"
  name = "Про мене"
  url = "about"
  weight = 10

[[main]]
  identifier = "archive"
  name = "Архів"
  url = "archive"
  weight = 2

#[[main]]
#  identifier = "presentation"
#  name = "Презентації"
#  url = "presentation"
#  weight = 3
#
#[[main]]
#  identifier = "gallery"
#  name = "Галерея"
#  url = "gallery"
#  weight = 4
#    
#[[main]]
#  parent = "gallery"
#  name = "Малюнки"
#  url = "gallery/cartoon"
#
#[[main]]
#  parent = "gallery"
#  name = "Фото"
#  url = "gallery/photo"
#
[[main]]
  identifier = "posts"
  name = "Дописи"
  url = "posts"
  weight = 1

#[[main]]
#  identifier = "showcase"
#  name = "Вітрина"
#  url = "showcase"
#  weight = 6
#
#[[main]]
#  identifier = "publication"
#  name = "Публікації"
#  url = "publication"
#  weight = 7
##
# [[main]]
#  identifier = "resume"
#  name = "CV"
#  url = "resume"
#  weight = 8
